export const ROUTES = {
  HOME: "/",
  PRICING: "/pricing",
  CONTACT: "/contact",
  LOGIN: "/login",
  SIGNUP: "/signup",
  GYM: (slug: string) => `/g/${slug}`,
  GYM_WORKOUTS: (slug: string) => `/g/${slug}/workouts`,
  GYM_WORKOUT: (slug: string, id: string) => `/g/${slug}/workouts/${id}`,
  GYM_SESSION: (slug: string, id: string) => `/g/${slug}/workouts/${id}/session`,
  GYM_PROGRESS: (slug: string) => `/g/${slug}/progress`,
  GYM_HISTORY: (slug: string) => `/g/${slug}/history`,
  GYM_ADMIN: "/gym-admin",
  GYM_ADMIN_MEMBERS: "/gym-admin/members",
  GYM_ADMIN_WORKOUTS: "/gym-admin/workouts",
  GYM_ADMIN_ANALYTICS: "/gym-admin/analytics",
  GYM_ADMIN_SETTINGS: "/gym-admin/settings",
  ONBOARD: "/onboard",
  SUPER_ADMIN: "/super-admin",
  SUPER_ADMIN_GYMS: "/super-admin/gyms",
  SUPER_ADMIN_SUBSCRIPTIONS: "/super-admin/subscriptions",
  SUPER_ADMIN_SUPPORT: "/super-admin/support",
  GYM_ATTEND: (slug: string) => `/g/${slug}/attend`,
  GYM_ADMIN_QR: "/gym-admin/qr",
  GYM_ADMIN_ATTENDANCE: "/gym-admin/attendance",
  GYM_ADMIN_SCANNER: "/gym-admin/scanner",
  GYM_ME: (slug: string) => `/g/${slug}/me`,
} as const;
