import type { Workout } from "@/types";

const TENANT_ID = "tenant-iron-house";

export const mockWorkouts: Workout[] = [
  // ─── WARMUP ───────────────────────────────────────────────────────────────
  {
    id: "workout-dynamic-warmup",
    tenantId: TENANT_ID,
    slug: "dynamic-warmup-flow",
    title: "Dynamic Warmup Flow",
    description: "A full-body activation sequence to prime your joints and muscles before any training session.",
    category: "Warmup",
    difficulty: "beginner",
    estimatedMinutes: 10,
    isFeatured: false,
    isQuickStart: true,
    isPublished: true,
    sourceType: "tenant",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    steps: [
      { id: "s-dw-1", workoutId: "workout-dynamic-warmup", exerciseId: null, order: 1, title: "Arm Circles", description: "Stand with feet shoulder-width apart. Extend both arms out to the sides and make large, controlled circles. Forward for 15 reps, then reverse for 15 reps.", mediaUrl: null, durationSeconds: null, reps: 15, sets: 2, restSeconds: 15 },
      { id: "s-dw-2", workoutId: "workout-dynamic-warmup", exerciseId: null, order: 2, title: "Hip Circles", description: "Stand with hands on hips. Make large, slow circles with your hips. Keep your upper body stable and your feet planted.", mediaUrl: null, durationSeconds: 30, reps: null, sets: null, restSeconds: 10 },
      { id: "s-dw-3", workoutId: "workout-dynamic-warmup", exerciseId: null, order: 3, title: "Leg Swings", description: "Hold a wall for balance. Swing one leg forward and back in a controlled arc. Keep the swing smooth, not forced. Switch legs after each set.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 2, restSeconds: 10 },
      { id: "s-dw-4", workoutId: "workout-dynamic-warmup", exerciseId: null, order: 4, title: "High Knees", description: "Run in place, driving your knees up to hip height on each step. Pump your arms in sync. Keep a light, bouncy rhythm.", mediaUrl: null, durationSeconds: 30, reps: null, sets: null, restSeconds: 15 },
      { id: "s-dw-5", workoutId: "workout-dynamic-warmup", exerciseId: null, order: 5, title: "Thoracic Rotations", description: "Get into a half-kneeling position. Place one hand behind your head and rotate your elbow toward the ceiling. Open up your upper back fully on each rep.", mediaUrl: null, durationSeconds: null, reps: 10, sets: 2, restSeconds: 15 },
    ],
  },

  // ─── CHEST ────────────────────────────────────────────────────────────────
  {
    id: "workout-dumbbell-chest-press",
    tenantId: TENANT_ID,
    slug: "dumbbell-chest-press",
    title: "Dumbbell Chest Press",
    description: "A beginner-friendly chest session using dumbbells to build foundational pressing strength and muscle.",
    category: "Chest",
    difficulty: "beginner",
    estimatedMinutes: 25,
    isFeatured: true,
    isQuickStart: true,
    isPublished: true,
    sourceType: "tenant",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    steps: [
      { id: "s-dcp-1", workoutId: "workout-dumbbell-chest-press", exerciseId: null, order: 1, title: "Flat Dumbbell Press", description: "Lie on a flat bench holding dumbbells at chest height, palms facing forward. Press up until arms are extended, then lower slowly. Keep shoulder blades pinched throughout.", mediaUrl: null, durationSeconds: null, reps: 10, sets: 3, restSeconds: 60 },
      { id: "s-dcp-2", workoutId: "workout-dumbbell-chest-press", exerciseId: null, order: 2, title: "Incline Dumbbell Press", description: "Set the bench to a 30–45° incline. Press the dumbbells from upper-chest height upward. This targets the upper pec and front delt.", mediaUrl: null, durationSeconds: null, reps: 10, sets: 3, restSeconds: 60 },
      { id: "s-dcp-3", workoutId: "workout-dumbbell-chest-press", exerciseId: null, order: 3, title: "Dumbbell Chest Fly", description: "Lie flat with arms extended above your chest, palms facing each other. Lower both arms in a wide arc until you feel a stretch across your chest, then bring them back together.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 45 },
      { id: "s-dcp-4", workoutId: "workout-dumbbell-chest-press", exerciseId: null, order: 4, title: "Close-Grip Dumbbell Press", description: "Lie flat and press the dumbbells together at chest level. Press straight up keeping the bells touching. Shifts emphasis to the inner chest and triceps.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 2, restSeconds: 45 },
      { id: "s-dcp-5", workoutId: "workout-dumbbell-chest-press", exerciseId: null, order: 5, title: "Push-Up Finisher", description: "Finish with bodyweight push-ups. Standard grip, full range of motion. Focus on squeezing the chest at the top of each rep.", mediaUrl: null, durationSeconds: null, reps: 15, sets: 2, restSeconds: 30 },
    ],
  },
  {
    id: "workout-pushup-burn",
    tenantId: TENANT_ID,
    slug: "push-up-burn",
    title: "Push-Up Burn",
    description: "An equipment-free chest and tricep burner using progressive push-up variations.",
    category: "Chest",
    difficulty: "intermediate",
    estimatedMinutes: 20,
    isFeatured: false,
    isQuickStart: false,
    isPublished: true,
    sourceType: "tenant",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    steps: [
      { id: "s-pub-1", workoutId: "workout-pushup-burn", exerciseId: null, order: 1, title: "Standard Push-Up", description: "Hands slightly wider than shoulder-width, body in a straight plank. Lower until your chest nearly touches the floor, then press up. Control the descent.", mediaUrl: null, durationSeconds: null, reps: 15, sets: 3, restSeconds: 40 },
      { id: "s-pub-2", workoutId: "workout-pushup-burn", exerciseId: null, order: 2, title: "Wide-Grip Push-Up", description: "Set your hands wider than a standard push-up. This wider stance increases the stretch across the chest at the bottom. Control each rep.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 40 },
      { id: "s-pub-3", workoutId: "workout-pushup-burn", exerciseId: null, order: 3, title: "Diamond Push-Up", description: "Form a diamond shape with your thumbs and index fingers beneath your chest. Lower down, then press up. Heavy tricep involvement.", mediaUrl: null, durationSeconds: null, reps: 10, sets: 3, restSeconds: 60 },
      { id: "s-pub-4", workoutId: "workout-pushup-burn", exerciseId: null, order: 4, title: "Decline Push-Up", description: "Elevate your feet on a bench or step. Perform push-ups from this position to target the upper chest and increase overall difficulty.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 60 },
      { id: "s-pub-5", workoutId: "workout-pushup-burn", exerciseId: null, order: 5, title: "Slow Negative Push-Up", description: "Take 4 full seconds to lower yourself to the floor, then press back up normally. This eccentric loading creates deep muscle fatigue.", mediaUrl: null, durationSeconds: null, reps: 8, sets: 2, restSeconds: 60 },
    ],
  },

  // ─── BACK ─────────────────────────────────────────────────────────────────
  {
    id: "workout-pull-up-strength",
    tenantId: TENANT_ID,
    slug: "pull-up-strength",
    title: "Pull-Up Strength",
    description: "Build pulling strength and back width through a structured pull-up progression and accessory work.",
    category: "Back",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    isFeatured: true,
    isQuickStart: false,
    isPublished: true,
    sourceType: "tenant",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    steps: [
      { id: "s-pus-1", workoutId: "workout-pull-up-strength", exerciseId: null, order: 1, title: "Dead Hang", description: "Grip the bar with both hands, palms facing away. Let your body hang fully, arms straight. Decompresses the spine and builds grip strength.", mediaUrl: null, durationSeconds: 30, reps: null, sets: 2, restSeconds: 45 },
      { id: "s-pus-2", workoutId: "workout-pull-up-strength", exerciseId: null, order: 2, title: "Scapular Pull-Up", description: "Hang from the bar with arms straight. Without bending your elbows, depress and retract your shoulder blades to pull your body up slightly.", mediaUrl: null, durationSeconds: null, reps: 10, sets: 3, restSeconds: 45 },
      { id: "s-pus-3", workoutId: "workout-pull-up-strength", exerciseId: null, order: 3, title: "Pull-Up", description: "Pull yourself up until your chin clears the bar. Lower slowly and with control. Use a band for assistance or perform slow negatives if needed.", mediaUrl: null, durationSeconds: null, reps: 6, sets: 3, restSeconds: 90 },
      { id: "s-pus-4", workoutId: "workout-pull-up-strength", exerciseId: null, order: 4, title: "Inverted Row", description: "Set a barbell in a rack at hip height. Lie underneath and grip the bar. Pull your chest up to the bar keeping your body rigid.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 60 },
      { id: "s-pus-5", workoutId: "workout-pull-up-strength", exerciseId: null, order: 5, title: "Band Pull-Apart", description: "Hold a resistance band at shoulder height with arms straight. Pull the band apart until it touches your chest, then return slowly.", mediaUrl: null, durationSeconds: null, reps: 15, sets: 3, restSeconds: 30 },
    ],
  },
  {
    id: "workout-cable-row",
    tenantId: TENANT_ID,
    slug: "seated-cable-row",
    title: "Seated Cable Row",
    description: "A focused back thickness session built around the seated cable row and dumbbell accessories.",
    category: "Back",
    difficulty: "beginner",
    estimatedMinutes: 25,
    isFeatured: false,
    isQuickStart: false,
    isPublished: true,
    sourceType: "tenant",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    steps: [
      { id: "s-cr-1", workoutId: "workout-cable-row", exerciseId: null, order: 1, title: "Seated Cable Row", description: "Sit at the cable station with feet planted. Pull the handle to your lower chest, driving elbows back and squeezing your shoulder blades together. Return with control.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 60 },
      { id: "s-cr-2", workoutId: "workout-cable-row", exerciseId: null, order: 2, title: "Lat Pulldown", description: "Grip the bar wider than shoulder-width. Pull it down to your upper chest while leaning back slightly. Squeeze the lats at the bottom and return slowly.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 60 },
      { id: "s-cr-3", workoutId: "workout-cable-row", exerciseId: null, order: 3, title: "Single-Arm Dumbbell Row", description: "Support yourself on a bench with one hand and one knee. Row the dumbbell from a full stretch up to your hip, keeping your back flat.", mediaUrl: null, durationSeconds: null, reps: 10, sets: 3, restSeconds: 60 },
      { id: "s-cr-4", workoutId: "workout-cable-row", exerciseId: null, order: 4, title: "Face Pull", description: "Set a cable to head height with a rope attachment. Pull the rope toward your face, separating the handles at the end. Targets rear delts and rotator cuff.", mediaUrl: null, durationSeconds: null, reps: 15, sets: 3, restSeconds: 45 },
    ],
  },

  // ─── LEGS ─────────────────────────────────────────────────────────────────
  {
    id: "workout-leg-day-starter",
    tenantId: TENANT_ID,
    slug: "leg-day-starter",
    title: "Leg Day Starter",
    description: "A foundational lower body session covering all major leg muscle groups with manageable volume.",
    category: "Legs",
    difficulty: "beginner",
    estimatedMinutes: 35,
    isFeatured: true,
    isQuickStart: false,
    isPublished: true,
    sourceType: "tenant",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    steps: [
      { id: "s-lds-1", workoutId: "workout-leg-day-starter", exerciseId: null, order: 1, title: "Bodyweight Squat", description: "Stand with feet shoulder-width apart. Lower your hips back and down until your thighs are parallel to the floor. Drive through your heels to stand.", mediaUrl: null, durationSeconds: null, reps: 15, sets: 3, restSeconds: 45 },
      { id: "s-lds-2", workoutId: "workout-leg-day-starter", exerciseId: null, order: 2, title: "Romanian Deadlift", description: "Hold dumbbells in front of your thighs. Hinge at the hips, pushing them back while lowering the weights along your legs. Feel the hamstring stretch, then drive hips forward.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 60 },
      { id: "s-lds-3", workoutId: "workout-leg-day-starter", exerciseId: null, order: 3, title: "Leg Press", description: "Sit in the leg press machine with feet hip-width apart. Lower the sled until your knees hit 90°, then press back up without locking out.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 60 },
      { id: "s-lds-4", workoutId: "workout-leg-day-starter", exerciseId: null, order: 4, title: "Leg Curl", description: "Lie face-down on the leg curl machine. Curl your heels toward your glutes through the full range of motion. Squeeze at the top, lower slowly.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 45 },
      { id: "s-lds-5", workoutId: "workout-leg-day-starter", exerciseId: null, order: 5, title: "Standing Calf Raise", description: "Stand on the edge of a step or flat ground. Rise onto your toes as high as possible, hold for a beat, then lower. Calves respond well to full range of motion.", mediaUrl: null, durationSeconds: null, reps: 20, sets: 3, restSeconds: 30 },
    ],
  },
  {
    id: "workout-squat-lunge-circuit",
    tenantId: TENANT_ID,
    slug: "squat-lunge-circuit",
    title: "Squat & Lunge Circuit",
    description: "An intermediate lower body circuit combining barbell squats, lunges, and explosive movements.",
    category: "Legs",
    difficulty: "intermediate",
    estimatedMinutes: 30,
    isFeatured: false,
    isQuickStart: false,
    isPublished: true,
    sourceType: "tenant",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    steps: [
      { id: "s-slc-1", workoutId: "workout-squat-lunge-circuit", exerciseId: null, order: 1, title: "Barbell Back Squat", description: "Bar rests across your upper traps. Feet shoulder-width, toes slightly out. Squat below parallel, keeping your chest tall and knees tracking over toes.", mediaUrl: null, durationSeconds: null, reps: 8, sets: 4, restSeconds: 90 },
      { id: "s-slc-2", workoutId: "workout-squat-lunge-circuit", exerciseId: null, order: 2, title: "Walking Lunge", description: "Step forward and lower your back knee toward the floor. Push off your front foot and step through into the next lunge. Keep your torso upright.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 60 },
      { id: "s-slc-3", workoutId: "workout-squat-lunge-circuit", exerciseId: null, order: 3, title: "Bulgarian Split Squat", description: "Rear foot elevated on a bench behind you. Lower your back knee toward the ground while keeping your front shin vertical.", mediaUrl: null, durationSeconds: null, reps: 10, sets: 3, restSeconds: 60 },
      { id: "s-slc-4", workoutId: "workout-squat-lunge-circuit", exerciseId: null, order: 4, title: "Box Jump", description: "Stand in front of a sturdy box. Dip into a quarter squat and jump onto the box landing softly. Step down — do not jump down.", mediaUrl: null, durationSeconds: null, reps: 8, sets: 3, restSeconds: 90 },
      { id: "s-slc-5", workoutId: "workout-squat-lunge-circuit", exerciseId: null, order: 5, title: "Wall Sit", description: "Lower into a squat position with your back flat against a wall, thighs parallel to the floor. Hold the position for the full duration.", mediaUrl: null, durationSeconds: 45, reps: null, sets: 3, restSeconds: 60 },
    ],
  },

  // ─── CARDIO ───────────────────────────────────────────────────────────────
  {
    id: "workout-treadmill-fat-burn",
    tenantId: TENANT_ID,
    slug: "treadmill-fat-burn",
    title: "Treadmill Fat Burn",
    description: "A structured 30-minute treadmill session with alternating intensity zones for fat burning.",
    category: "Cardio",
    difficulty: "beginner",
    estimatedMinutes: 30,
    isFeatured: false,
    isQuickStart: true,
    isPublished: true,
    sourceType: "tenant",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    steps: [
      { id: "s-tfb-1", workoutId: "workout-treadmill-fat-burn", exerciseId: null, order: 1, title: "Easy Walk — Warm-Up", description: "Start at a comfortable walking pace (4–5 km/h). Keep your posture tall, shoulders relaxed, arms swinging naturally.", mediaUrl: null, durationSeconds: 300, reps: null, sets: null, restSeconds: null },
      { id: "s-tfb-2", workoutId: "workout-treadmill-fat-burn", exerciseId: null, order: 2, title: "Moderate Jog", description: "Increase to a light jog (7–8 km/h). You should be able to speak in short sentences. Maintain a comfortable, sustainable pace.", mediaUrl: null, durationSeconds: 600, reps: null, sets: null, restSeconds: null },
      { id: "s-tfb-3", workoutId: "workout-treadmill-fat-burn", exerciseId: null, order: 3, title: "Power Walk Intervals", description: "Increase incline to 4–6%. Walk at a brisk pace (5.5–6 km/h). The incline significantly increases calorie burn without the impact of running.", mediaUrl: null, durationSeconds: 300, reps: null, sets: null, restSeconds: null },
      { id: "s-tfb-4", workoutId: "workout-treadmill-fat-burn", exerciseId: null, order: 4, title: "Run — Push Phase", description: "Drop incline back to flat. Increase speed to a run you can sustain (9–10 km/h). Push yourself here — this is the high-intensity block.", mediaUrl: null, durationSeconds: 300, reps: null, sets: null, restSeconds: null },
      { id: "s-tfb-5", workoutId: "workout-treadmill-fat-burn", exerciseId: null, order: 5, title: "Cool Down Walk", description: "Reduce speed to an easy walk (4 km/h). Allow your heart rate to come down gradually. Keep moving — stopping abruptly is not ideal for recovery.", mediaUrl: null, durationSeconds: 300, reps: null, sets: null, restSeconds: null },
    ],
  },
  {
    id: "workout-hiit-cardio-blast",
    tenantId: TENANT_ID,
    slug: "hiit-cardio-blast",
    title: "HIIT Cardio Blast",
    description: "High-intensity intervals using bodyweight movements. Maximum effort, minimum equipment.",
    category: "Cardio",
    difficulty: "advanced",
    estimatedMinutes: 25,
    isFeatured: true,
    isQuickStart: false,
    isPublished: true,
    sourceType: "tenant",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    steps: [
      { id: "s-hcb-1", workoutId: "workout-hiit-cardio-blast", exerciseId: null, order: 1, title: "Jump Squats", description: "Squat down and explode upward into a jump. Land softly with slightly bent knees and go straight into the next rep.", mediaUrl: null, durationSeconds: 40, reps: null, sets: 4, restSeconds: 20 },
      { id: "s-hcb-2", workoutId: "workout-hiit-cardio-blast", exerciseId: null, order: 2, title: "Burpees", description: "Drop hands to floor, jump feet back to plank, perform a push-up, jump feet forward, then explode into a jump with arms overhead.", mediaUrl: null, durationSeconds: 40, reps: null, sets: 4, restSeconds: 20 },
      { id: "s-hcb-3", workoutId: "workout-hiit-cardio-blast", exerciseId: null, order: 3, title: "Mountain Climbers", description: "Start in a plank position. Alternate driving each knee toward your chest at high speed. Keep your hips low and your core braced.", mediaUrl: null, durationSeconds: 40, reps: null, sets: 4, restSeconds: 20 },
      { id: "s-hcb-4", workoutId: "workout-hiit-cardio-blast", exerciseId: null, order: 4, title: "Jump Rope (or Simulation)", description: "Jump rope or simulate the motion by hopping in place while swinging your wrists. Maintain a quick, rhythmic tempo.", mediaUrl: null, durationSeconds: 40, reps: null, sets: 4, restSeconds: 20 },
      { id: "s-hcb-5", workoutId: "workout-hiit-cardio-blast", exerciseId: null, order: 5, title: "Sprint in Place", description: "Run as fast as you can in place. Drive your knees up high and pump your arms hard. Give everything you have for the full duration.", mediaUrl: null, durationSeconds: 40, reps: null, sets: 4, restSeconds: 60 },
    ],
  },

  // ─── FULL BODY ────────────────────────────────────────────────────────────
  {
    id: "workout-kettlebell-conditioning",
    tenantId: TENANT_ID,
    slug: "kettlebell-conditioning",
    title: "Kettlebell Conditioning",
    description: "A full-body kettlebell session that builds strength, power, and conditioning simultaneously.",
    category: "Full Body",
    difficulty: "intermediate",
    estimatedMinutes: 35,
    isFeatured: true,
    isQuickStart: false,
    isPublished: true,
    sourceType: "tenant",
    createdAt: "2025-01-01T00:00:00.000Z",
    updatedAt: "2025-01-01T00:00:00.000Z",
    steps: [
      { id: "s-kbc-1", workoutId: "workout-kettlebell-conditioning", exerciseId: null, order: 1, title: "Kettlebell Swing", description: "Hinge at the hips and swing the bell between your legs. Drive your hips forward powerfully to project the bell up to chest height. This is a hip hinge, not a squat.", mediaUrl: null, durationSeconds: null, reps: 15, sets: 4, restSeconds: 60 },
      { id: "s-kbc-2", workoutId: "workout-kettlebell-conditioning", exerciseId: null, order: 2, title: "Goblet Squat", description: "Hold the kettlebell by the horns at chest height. Squat deep with your elbows inside your knees at the bottom. Keep your chest tall and drive through your heels.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 60 },
      { id: "s-kbc-3", workoutId: "workout-kettlebell-conditioning", exerciseId: null, order: 3, title: "KB Clean & Press", description: "Clean the bell to the rack position in one fluid motion, then press it overhead. Perform all reps on one side before switching.", mediaUrl: null, durationSeconds: null, reps: 8, sets: 3, restSeconds: 90 },
      { id: "s-kbc-4", workoutId: "workout-kettlebell-conditioning", exerciseId: null, order: 4, title: "KB Romanian Deadlift", description: "Hold the bell in both hands. Hinge at your hips with a flat back, lowering the bell between your legs until you feel a deep hamstring stretch.", mediaUrl: null, durationSeconds: null, reps: 12, sets: 3, restSeconds: 60 },
      { id: "s-kbc-5", workoutId: "workout-kettlebell-conditioning", exerciseId: null, order: 5, title: "KB Farmer's Carry", description: "Hold a kettlebell in each hand at your sides. Walk for the full duration with shoulders back, core braced, and a tall posture.", mediaUrl: null, durationSeconds: 40, reps: null, sets: 3, restSeconds: 45 },
    ],
  },
];
